### ISSUE TITLE
Crash: when switching to 24.04 on the app

### ISSUE THREAD

**Issue by notIkibo** [newhinton/Timed-Silence#10]
Situation: I deleted any preconfigurated time. I made a new rule: Every wednesday 13:30 - 18:30 silence.

Problem: When I now wanted to see how my Wednesday will look like in the App (24.04),cit instantly crashes.

When I delete the rule: No crash occurs. Haven't tried every weekday, but Thursday is safe.

I really need this app to work. It sounds like a must-have. 

![logcat.txt](https://github.com/newhinton/Timed-Silence/files/15081195/logcat.txt)

**Comment by notIkibo** [comment]
For log I used logcat app with timedsilence keyword filtered

**Comment by newhinton** [comment]
Is the wednesday-rule the only one?

Can you post some details of your device?
Maker, Model, Android Version?

**Comment by newhinton** [comment]
https://github.com/newhinton/Timed-Silence/issues/8#issuecomment-2072934409

Check that comment, this looks like the same issue.

**Comment by newhinton** [comment]
@notIkibo If you do test the apk, please report back your results in the other ticket, it is greatly appreciated!
