### ISSUE TITLE
Please trigger a new update on F-droid

### ISSUE THREAD

**Issue by thanhminhmr** [newhinton/Timed-Silence#12]
Can you please trigger a manual update on F-droid repository?

I'm patiently waiting for like 2 weeks and F-droid is still not updating the hot fix. Version 3.1.1 still crash everytime you open the app, so it's not working at all for me.

And please do trigger a manual update everytime you have to push a hotfix for an app-breaking bug.

**Comment by newhinton** [comment]
I'll have to check why fdroid isn't picking up my tags.

However, you can always just use the github release apk, it is signed with the same key f-droid uses.

**Comment by fabolhak** [comment]
I really like the app, but currently only the bugged version 3.1.1 is available on F-Droid. I downloaded 3.1.2 from Github and I'm very happy with it. Not sure how many other users will go the extra mile and check on GitHub though.

**Comment by newhinton** [comment]
Should be in the build pipeline now, so a new release should show up in the next days.
