### ISSUE TITLE
please grant permission is over the permission

### ISSUE THREAD

**Issue by nutpantz** [newhinton/Timed-Silence#3]
![Screenshot_20240416-092339](https://github.com/newhinton/Timed-Silence/assets/12160507/ac823a8a-ff8b-4c85-82ea-a9b57e109c8a)

Can't grant

**Comment by newhinton** [comment]
The permission model is not perfect. Sadly, the calendar request pops up multiple times. You can "grant" all of them, then they vanish and the other one becomes accessible.

**Comment by newhinton** [comment]
Fixed 24283b8864fd591738772de322449a06e531bc7a
