### ISSUE TITLE
FR: Do not force-require nearby devices permission

### ISSUE THREAD

**Issue by Zocker1999NET** [newhinton/Timed-Silence#6]
The app seems to require the nearby devices permission. That makes sense for detecting Bleutooth devices, but this should not be required when users do not want to use that feature.
Further, the dialog from the app before asks for the calendar permission which was granted.

<details><summary>Screenshots</summary>
<p>

![IMG_20240417_150945](https://github.com/newhinton/Timed-Silence/assets/1645646/264a8e62-a13e-4d2d-ae93-70ea37e0f610)
![IMG_20240417_151022](https://github.com/newhinton/Timed-Silence/assets/1645646/0ed0e1ae-97a7-4276-a522-64e6bd5eaf79)
![IMG_20240417_151009](https://github.com/newhinton/Timed-Silence/assets/1645646/2bc3a15c-1b32-4e8e-acea-7a473e3c83a3)

</p>
</details>

**Comment by newhinton** [comment]
Yeah, the permission handling was a bit all over the place.

I cleaned it up earlier today, it's already releases in 3.1.0

Fixed in 24283b8864fd591738772de322449a06e531bc7a
