### ISSUE TITLE
Can't select a calendar

### ISSUE THREAD

**Issue by nizarus** [newhinton/Timed-Silence#7]
When trying to select a calendar the dialog to select one is displayed (screen capture attached) but no action is taken by the app when I select one – Yes, I have a long list of calendar.
![ResizedImage_2024-04-21_19-21-46_1739](https://github.com/newhinton/Timed-Silence/assets/17108772/4800e38a-24fe-48ba-90a9-93a6c66c79b1)

**Comment by newhinton** [comment]
Ah, i see. 

No worries, i dont judge your calendar list, i have also quite a few. However, not enough to push the buttons out of the dialog, which seems to be the case here. That should be a rather easy fix.

**Comment by newhinton** [comment]
Fixed in 5ba4db28462c4e9fad3751bc32bda41d08661a2d
