### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [newhinton/Timed-Silence#9]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6684357466#L1036

Diff is small:
```
│ │ │ │   --- TimedSilence-release-v3.1.1/res/layout/customui_radiobutton.xml
│ │ │ ├── +++ de.felixnuesse.timedsilence_7/res/layout/customui_radiobutton.xml
│ │ │ │ @@ -1,2 +1,2 @@
│ │ │ │  <?xml version="1.0" encoding="utf-8"?>
│ │ │ │ -<RadioButton xmlns:android="http://schemas.android.com/apk/res/android" android:id="@id/radioButton" android:layout_width="fill_parent" android:layout_height="64.0dip"/>
│ │ │ │ +<RadioButton xmlns:android="http://schemas.android.com/apk/res/android" android:id="@id/radioButton" android:layout_width="fill_parent" android:layout_height="32.0dip"/>
```

**Comment by newhinton** [comment]
Ahh sorry, must have overlooked that a file was still changed. Can i just rebuild 3.1.1 locally and update the release apk for this to go through?

**Comment by licaon-kter** [comment]
Yup, ping me when done

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/801623e6c234491eda2aec6e31ae80bcec7118e7

**Comment by TotallyAvailable** [comment]
@newhinton ***Please*** remember to set the GITHUB_TOKEN permissions for the workflow to the ***absolute minimum*** necessary, ideally before you resume them with an updated 'upload-artifact' version. This suggestion obviously applies to any potential future ones used to build the app as well.

The current default/undefined state results in a token with **write-all** permission...
